# Generated by Django 2.0.5 on 2018-06-03 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_fallecimiento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_fallecimiento', models.DateField(blank=True, null=True)),
                ('es_actor', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Escribe un género de película.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('URLcontenido', models.CharField(max_length=200)),
                ('descripcion', models.TextField(help_text='Escribe una descripción de la película', max_length=1000)),
                ('anyo', models.DateField()),
                ('URLportada', models.CharField(max_length=200)),
                ('valoracion', models.DecimalField(decimal_places=1, max_digits=2)),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='videoclub.Director')),
                ('genero', models.ManyToManyField(help_text='Introduce genero', to='videoclub.Genero')),
                ('reparto', models.ManyToManyField(help_text='Introduce actor(es)', to='videoclub.Actor')),
            ],
        ),
    ]
