# Generated by Django 2.0.5 on 2018-06-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('videoclub', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Director',
            new_name='Persona',
        ),
        migrations.RemoveField(
            model_name='instanciapelicula',
            name='status',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='sumario',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='descripcion',
            field=models.TextField(default='', help_text='Introduce una descripcion para la película', max_length=1000),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='reparto',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='urlPortada',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='valoracion',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='genero',
            name='name',
            field=models.CharField(help_text='Introduzca un genero de película', max_length=200),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='titulo',
            field=models.CharField(default='', max_length=200),
        ),
    ]
