# Generated by Django 2.0.5 on 2018-06-21 22:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_de_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_de_defuncion', models.DateField(blank=True, null=True, verbose_name='Fallecido')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Introduzca un genero de película (Ciencia ficción, Drama, etc.)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InstanciaPelicula',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único para esta pelicula en particular en todo el videoclub', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='m', help_text='Disponibilidad del libro', max_length=1)),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('sinopsis', models.TextField(help_text='Descripción breve del argumento de la pelicula', max_length=1000)),
                ('isbn', models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, verbose_name='ISBN')),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='videoclub.Director')),
                ('genero', models.ManyToManyField(help_text='Selecciona un género para esta pelicula', to='videoclub.Genero')),
            ],
        ),
        migrations.AddField(
            model_name='instanciapelicula',
            name='pelicula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='videoclub.Pelicula'),
        ),
    ]
