# Generated by Django 2.0.5 on 2018-06-25 22:56

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ('videoclub', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Director',
            new_name='Persona',
        ),
    ]
