# Generated by Django 2.0.5 on 2018-06-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoclub', '0002_auto_20180627_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
