# Generated by Django 2.0.5 on 2018-06-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoclub', '0004_auto_20180629_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='año',
            field=models.DateField(blank=True, null=True),
        ),
    ]
