# Generated by Django 2.0.5 on 2018-06-28 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoclub', '0005_pelicula_año'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instanciapelicula',
            name='pelicula',
        ),
        migrations.DeleteModel(
            name='InstanciaPelicula',
        ),
    ]
