# Generated by Django 2.0.5 on 2018-06-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoclub', '0006_auto_20180629_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='valoracion',
            field=models.PositiveIntegerField(help_text='si/no , en minusculas todo'),
        ),
    ]
