# Generated by Django 2.0.5 on 2018-06-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoclub', '0007_auto_20180629_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='valoracion',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='persona',
            name='esDirector',
            field=models.CharField(default='no', help_text='si/no , en minusculas todo', max_length=2),
        ),
    ]
