# Generated by Django 2.0.5 on 2018-06-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoclub', '0008_auto_20180629_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='urlPortada',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
