# Generated by Django 2.0.5 on 2018-06-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoclub', '0009_auto_20180629_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='urlPortada',
            field=models.CharField(default='', max_length=200),
        ),
    ]
