# Generated by Django 2.0.5 on 2018-06-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoclub', '0011_auto_20180629_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='reparto',
            field=models.ManyToManyField(to='videoclub.Persona'),
        ),
    ]
