# Generated by Django 2.0.5 on 2018-06-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoclub', '0012_auto_20180629_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='first_name',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='valoracion',
            field=models.PositiveIntegerField(help_text='Valor de 0-100'),
        ),
    ]
