# Generated by Django 2.0.5 on 2018-07-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoclub', '0014_auto_20180701_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='urlFoto',
            field=models.CharField(default='https://www.w3schools.com/css/img_avatar.png', max_length=200),
        ),
    ]
