# Generated by Django 2.0.5 on 2018-07-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoclub', '0015_auto_20180702_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='urlVideo',
            field=models.CharField(default='https://www.youtube.com/embed/_nq2BTuSOq4', max_length=200),
        ),
    ]
