# Generated by Django 2.0.5 on 2018-06-03 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoclub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='director',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genero',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genero',
            name='name',
            field=models.CharField(help_text='Escribe un género cinematográfico.', max_length=200),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='anyo',
            field=models.DateField(help_text='Año del estreno de la película'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='descripcion',
            field=models.TextField(help_text='Descripción de la película', max_length=1000),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='director',
            field=models.ForeignKey(help_text='Director de la película', null=True, on_delete=django.db.models.deletion.SET_NULL, to='videoclub.Director'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.ManyToManyField(help_text='Género cinematográfico en el que se clasifica la película', to='videoclub.Genero'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='nombre',
            field=models.CharField(help_text='Nombre original de la película', max_length=200),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='reparto',
            field=models.ManyToManyField(help_text='Actores que aparecen oficialmente en la película', to='videoclub.Actor'),
        ),
    ]
